clients/extjs/js/collectionReview.js

- Fix #32 
- Make Rule/title the default view
- Filtering combinations now work as expected
- Rule detail panel now matches the one in Review workspace
This workspace has additional issues. We need to better handle filtering that removes the currently selected record. Currently, the selection is removed but the child grids continue to display the old selected record details.

Collection review fixes

---

api/source/service/mysql/migrations/0005.js
api/source/service/mysql/migrations/sql/0005/down/10-v-current-rev.sql
api/source/service/mysql/migrations/sql/0005/up/10-v-current-rev.sql

The view `v_current_rev` is used to materialize the table `current_rev` which is queried to retrieve a list of STIGs and their current revisions. The view only returns revisions with status 'accepted'. Therefore a STIG whose only available revision has status 'draft' will not appear in `current_rev`.
The view definition has been modified to fix this and MySQL migration 0005 has been created. This serves as a foundation for further refinement of Draft STIG handling.

Migration of v_current_rev

---

api/source/service/mysql/STIGService.js
api/source/service/mysql/migrations/0006.js
api/source/service/mysql/migrations/sql/0006/up/10-v-current-rev.sql
api/source/service/mysql/utils.js
api/source/specification/stig-manager.yaml
clients/extjs/js/stigAdmin.js

DISA releases SCAP content (a.k.a. "Benchmarks") where the benchmarkIds do not necessarily correspond to a manual STIG. The calculation of ovalCount did not account for this and has been revised.

ovalCount based on ruleId instead of benchmarkId

---

api/source/utils/auth.js

Handle the edge case where a token is issued with the scope value of empty string

(fix) Empty string scope not failing #42

---

clients/extjs/js/collectionReview.js

Set initial value for `groupGrid.titleColumnDataIndex` to 'ruleTitle'

fix: collection review filter (#64)

---

api/source/service/mysql/utils.js

Our mysql2 `options.typeCast` method didn't explicitly specify utf-8 encoding for JSON.parse(). But mysql2's built-in JSON typecaster already handles this properly, so our method is redundant and, rather than fix it, I have removed it..

Remove typeCast handling for JSON (#62)

---

clients/extjs/js/collectionReview.js

Addressed issue #120 by removing the Standard Feedback widget from the Collection Review workspace. Support for that concept was present in STIG Manager Classic but is absent from the REST API.

fix: Remove standard feedback widget (#120)

---

api/source/package-lock.json
api/source/package.json
api/source/service/mysql/utils.js

Some pilot deployments are stuck using MySQL 8.0.15. Rewrote one query to avoid using syntax introduced in 8.0.19. This query will need work again once the VALUES() function is removed by the MySQL team.

Support older MySQL syntax and check minimum version

---

clients/extjs/css/stigman.css
clients/extjs/js/RowEditor.js
clients/extjs/js/overrides.js

- z-index default set to 8000
- mask parent grid when editor is active
- lighten mask color to 666

fix: inline row editors

---

.github/workflows/pub-docker.yml

recent changes to documentation moved docker readme, breaking the push to docker hub

fix: Adjust path to docker readme  (#195)

---

api/source/service/mysql/migrations/0007.js

Migrates MySQL
This migration changes the collation of each `benchmarkId` column from `utf8mb4_0900_as_ci` to `utf8mb4_0900_as_cs`. This is a **potentially breaking change**, but the current beta pilot deployments are unlikely to have data old enough to be affected. Symptoms of an issue would probably involve Asset-STIG assignments and Status reporting.

feat: case-sensitive collation for benchmarkId

---

Dockerfile

fix: sticky bit for world-writable dirs created by npm

---

api/source/service/mysql/migrations/0008.js
api/source/specification/stig-manager.yaml
clients/extjs/js/SM/CollectionAsset.js

Changed asset name, ip, and mac varchar length to 255 in DB, added corresponding maxlength properties to API Spec. 
Removed ip validation from UI for modifying Assets, as this would prevent saving with multiple ips. 
Added nullable: true to collection description properties in api spec.
fixes #239 
fixes #246 
fixes #46

bug: Changed asset name, ip, and mac length to 255 in db and spec, added nullable property to collection description

---

clients/extjs/js/SM/CollectionAsset.js
clients/extjs/js/SM/CollectionStig.js
clients/extjs/js/overrides.js

Allow stores to be configured with smMaskDelay that suppresses showing a load mask until the configured number of milliseconds has elapsed.

feat: Ext.LoadMask looks for store.smMaskDelay

---

api/source/controllers/STIG.js
api/source/utils/fetchStigs.js
clients/extjs/js/stigmanUtils.js

Removed attempts to filter STIG processing based on filename (Aside from requiring a xml/XML extension), since they do not seem to follow any reliable convention. Restricted error responses to just parser error message (removed stack trace portion so it does not show up in user's import log).
fixes: #235

fix: Removed STIG filename filters 

---

api/source/controllers/Review.js
api/source/utils/parsers.js
clients/extjs/js/SM/Parsers.js
clients/extjs/js/SM/ReviewsImport.js

Fixes #275 
In an SCC XCCDF TestResult file, `<rule-result>` can sometimes lack a child `<check>`. Modified the parser so the generated `review.resultComment` property does not rely on `<check>`.

fix #275: handle rule-result without check

---

api/source/service/mysql/utils.js
api/source/specification/stig-manager.yaml
api/source/utils/parsers.js
clients/extjs/css/stigman.css
clients/extjs/js/SM/Global.js
clients/extjs/js/SM/Parsers.js
clients/extjs/js/SM/ReviewsImport.js
clients/extjs/js/review.js
clients/extjs/js/stigmanUtils.js

Fixes #67 
I've expanded the API to accept all nine (9) XCCDF result values, not just the three (3) compliance categories:
```
- fail
- pass
- notapplicable
- notchecked
- unknown
- error
- notselected
- informational
- fixed
```
I've also updated the CKL parsers in the API and Web Client to map `<STATUS>Not_Reviewed</STATUS>` where `<FINDING_DETAILS>` is not empty as result `informational`. All other `Not_Reviewed` reviews will continue to be ignored. 
The CKL exporter was already configured to map an `informational` result to `Not_Reviewed`.
The API will now accept `notchecked` as a valid result but for now our clients will not submit Reviews with that.

feat: Accept all XCCDF result values (#67)

---

clients/extjs/js/collectionReview.js
clients/extjs/js/review.js
clients/extjs/js/stigmanUtils.js

Displays of history now include the current state of the Review as the latest entry.
Renamed history tabs to "log"
fixes: #255

UI: History->log, now displays current state of Reviews as latest entry

---

api/source/controllers/STIG.js
api/source/specification/stig-manager.yaml
clients/extjs/js/SM/Parsers.js
clients/extjs/js/SM/ReviewsImport.js

Resolves #248 
The example given in the issue (RHEL_8_STIG => RHEL_8) no longer applies since V1R2 of the STIG changed the Manual benchmarkId. `GET stigs/scap-maps` returns a static array:
```
[
{
scapBenchmarkId: 'CAN_Ubuntu_18-04_STIG',
benchmarkId: 'U_CAN_Ubuntu_18-04_STIG'
},
{
scapBenchmarkId: 'Mozilla_Firefox_RHEL',
benchmarkId: 'Mozilla_Firefox'
},
{
scapBenchmarkId: 'Mozilla_Firefox_Windows',
benchmarkId: 'Mozilla_Firefox'
},
{
scapBenchmarkId: 'Solaris_10_X86_STIG',
benchmarkId: 'Solaris_10_X86'
}
]
```

SCAP BenchmarkId Map

---

api/source/controllers/Asset.js
api/source/controllers/Collection.js
api/source/service/mysql/AssetService.js
api/source/service/mysql/CollectionService.js
api/source/specification/stig-manager.yaml
test/api/postman_collection.json

resolves #316
note: the GETs asset tests have the checks for content comment out - since the assets metadata is {}. not sure how to get the column prepopulated. can discuss further.

Adds metadata handling for Assets and Collections

---

api/source/service/mysql/STIGService.js

delete stig now deletes records in related tables and updates statistics

---

api/source/controllers/Collection.js
api/source/service/mysql/CollectionService.js
api/source/specification/stig-manager.yaml
api/source/utils/accessLevels.js

resolves #331 
GET /collections/{collectionId}/review-history
Available to all users with a grant to the collection. For level 1 users, only entries that fall under their Asset-STIG grants should be returned.
Returns block of review history entries that fit criteria. Takes optional:
Start Date
End Date
(If no dates provided, return all history. If only one date, return block from that date to current, or that date to oldest, as appropriate)
Asset ID - only return history for this asset id
Rule ID - only return history for this rule id
status- only return history with this status
If rule and asset id provided, return that intersection.
DELETE /collections/{collectionId}/review-history
Available only to level 3 or 4 users ("Manage" or "Owner")
Returns number of history entries deleted. …

Adds new review-history endpoints

---

api/source/controllers/Asset.js
test/api/postman_collection.json

Also fixed tests so they should identify this issue if it regresses in future.

fix: query param inadvertently marked as path param in Asset/getChecklistByAsset

---

api/source/service/mysql/AssetService.js
api/source/service/mysql/CollectionService.js
api/source/specification/stig-manager.yaml
clients/extjs/js/SM/CollectionAsset.js
clients/extjs/js/SM/Exports.js
clients/extjs/js/SM/ReviewsImport.js
test/api/postman_collection.json

Resolves #438
`adminStats` projection of `GET /assets` and `GET /assets/{assetId}` changed to `statusStats` and includes `rejectedCount`, `minTs` and `maxTs`
Added `rejectedCount`, `minTs` and `maxTs` to object returned by `GET /collections/{collectionId}/stigs`

OAS, API, test, and UI for statusStats with rejectedCount, minTs, maxTs

---

api/source/controllers/Operation.js
api/source/index.js
api/source/specification/stig-manager.yaml
api/source/utils/auth.js
api/source/utils/config.js

The CORS proxy feature is experimental for use by deployments unable to control their OIDC Provider's CORS policy. The web client (UI) is configured to use the CORS proxy by setting:
```
STIGMAN_CLIENT_OIDC_PROVIDER = "api/op/cors-proxy/oidc"
```
The CORS proxy forwards incoming requests to the OIDC Provider configured by `STIGMAN_OIDC_PROVIDER`
Adds endpoints:
```
/op/cors-proxy/oidc/.well-known/openid-configuration
/op/cors-proxy/oidc/token
```
Adds optional envvar:
STIGMAN_OIDC_PROXY_HOST: **No default** The `Host:` header value to be used by the CORS proxy for outbound requests. Some OIDC providers return configuration metadata with endpoint URLs having this value as their base.

feat: experimental CORS proxy for OIDC

---

api/source/index.js
api/source/utils/config.js
clients/extjs/js/SM/MainPanel.js

Removes support for rendering HTML in `STIGMAN_CLIENT_WELCOME_MESSAGE`.
Adds envvars:
`STIGMAN_CLIENT_WELCOME_TITLE` **Default: "Support"** The title for the custom Welcome message.
`STIGMAN_CLIENT_WELCOME_LINK` **No default** The value of the optional anchor tag following the custom Welcome message.

feat: Welcome message enhancements

---

clients/extjs/js/SM/FindingsPanel.js

fix: encode office query param

---

.github/workflows/pub-docker-ib.yml
.github/workflows/pub-docker.yml
api/source/package-lock.json
api/source/package.json
docs/_build/html/_sources/the-project/DockerHub_Readme.md.txt
release-notes.rst

fix: filter grid on asset name (#498)
feat: UI support for STIG/revision delete (#491)
refactor: unhandled rejections (#490)
doc: Additional documentation updates, links. (#489)
doc: Added project security policy, security docs, docker trust public key, stigman sample .ckl (#486)
feat: choice to export mono- or multi-STIG CKLs (#480)
refactor: await _migrations table (#476)

chore: bump release to 1.0.41

---

.github/workflows/pub-docker-ib.yml
.github/workflows/pub-docker.yml
api/source/package-lock.json
api/source/package.json
release-notes.rst

Commits:
- #517
- #514
- #513
- #511
Includes breaking changes to the OpenAPI definition that affect clients such as [STIG Manager Watcher](https://github.com/NUWCDIVNPT/stigman-watcher). Some properties of the schemas for `Review...` and `ReviewHistory...` have been changed, renamed or removed:
- `resultComment` is renamed to `detail`
- `actionComment` is renamed to `comment`
- `action` is removed
- `status` value can be either a string or an object. See the definition for details.
Includes a MySQL migration that changes the schema for tables `review` and `reviewHistory`. 
- The running time of the migration depends on the number of records in those tables. 
- The migration also drops the small, static table `action`.
- We recommend backing up the database before updating to any release …

chore: bump release to 1.1.0

---

api/source/utils/fetchStigs.js

refactor fetchStigs() and fetchScap() to properly emit error objects

refactor: fetchStigs/Scap logging

---

api/source/package-lock.json
api/source/package.json
release-notes.rst

Hotfix release to fix a UI regresssion that incorrectly hides the "Accept" button and disables the "Reject" feature

hotfix: bump release to 1.2.2

---

api/source/package-lock.json
api/source/package.json
release-notes.rst

1.2.4
-----
Changes:
- (API/App) Endpoint and UI for deployment-wide usage statistics
- (App) CKL export fixes
- (App) Changed incorrectly named column headers on the Collection Manage workspace
- (API/App) Require a compliance result (pass, fail, notapplicable) to submit a Review
- (Docs) Updates regarding "submit" status requirements
Commits:
- 8f0905f docs: updates regarding "submit" status requirements (#595)
- 86a9890 fix: require a compliance result to submit review (#594)
- b506920 fix: headers don't match API (#592)
- 0c7ecf5 fix: CKL export fails to include all rules (#591)
- 98025ce feat: endpoint and ui for /op/details (#570)

chore: bump release to 1.2.4

---

client/src/js/SM/NavTree.js

The image source for `label.svg` in the Navigation Tree began with an incorrect `..` dot-component.

fix: modify path to label.svg in NavTree

---

api/launchers/stig-manager.sh
api/source/package-lock.json
api/source/package.json
client/src/js/SM/CollectionForm.js
client/src/js/SM/NavTree.js
docs/the-project/DockerHub_Readme.md
release-notes.rst

Includes:
- an update to the Docker Hub README
- a correction to the path for `img/color-picker.svg`
- minor corrections to the API's Linux build script

chore: bump release to 1.2.6

---

docs/_build/html/.gitignore

Docker builds will fail when `docs/_build/html` does not exist. This path was incorrectly removed by [62011d8](https://github.com/NUWCDIVNPT/stig-manager/commit/62011d851b7c0771cb3b1f3abce4e5554f44a07b). This commit stubs out the necessary path.

docs: include stub html directory

---

client/src/css/stigman.css
client/src/js/collectionReview.js
client/src/js/review.js

Resolves #636 
- In the Collection/STIG Review checklist grid, the columns that count O, NF, NA, and NR were expanded to accommodate up to 4 digits. These columns remain fixed width and are not re-sizable by the user.
- In both the Asset/STIG Review and Collection/STIG Review checklist grids, the default visible columns were changed from "Group ID and Group Title" to "Group ID and Rule Title". This more closely reflects the observed preferences of many users.

feat: widen columns; default to groupId/ruleTitle

---

api/source/service/mysql/CollectionService.js
api/source/service/mysql/STIGService.js
api/source/service/mysql/UserService.js
api/source/specification/stig-manager.yaml
api/source/utils/auth.js
test/api/postman_collection.json

Adjustments to OAS/API to bring the two into alignment.
**OAS**:
(Changes to OAS are to match what API is currently returning, to avoid issues in Clients at this time.)
**New schemas:** 
- BenchmarkId
**changed:**
- Findings Projected (this endpoint can return objects with many different structures/properties):
> **added**:
> assetCount
> cci
> title
> definition
> apAcronym
> groups
> rules
> stigs
> **removed**:
> ruleTitle
> groupTitle
- CciBasic:
> **added**:
> definition
> **removed**:
> control
- GroupProjected:
> **added**:
> severity
- RuleProjected:
> changed securityOverrideGuidance to severityOverrideGuidance
**API**:
(Most changes are to add data or change types so they match OAS spec. Avoid changing property names to avoid client issues)
**auth.js**:
added "email" to …

fix: Initial adjustments to OAS and API to bring the two into alignment.

---

api/source/service/mysql/CollectionService.js
api/source/service/mysql/STIGService.js
api/source/specification/stig-manager.yaml

resolves: #496 
**OAS**:
'/collections/{collectionId}/reviews/{assetId}/{ruleId}':
- added 204 response
'/collections/{collectionId}/labels':
- POST - changed response code from 200 to 201
'/collections/{collectionId}/labels/{labelId}':
- removed "array" type as this returns a single labels info.
'/collections/{collectionId}/labels/{labelId}/assets':
- PUT - changed response to array of AssetBasic, rather than strings
/stigs:
- POST - added STIGPostResponse since this endpoint returns very free-form progress info (for now)
STIGPostResponse:
type: object
/user
- changed schema to UserProjected, rather than just User.
Schemas:
- AssetBasicProjected:
> added:
>         collectionId:
>           type: string  #This is redundant except when in response to a request that changed an Asset's …

fix: further OAS/API reconciliation.

---

api/launchers/stig-manager.bat
api/launchers/stig-manager.sh
api/source/index.js
api/source/utils/auth.js
api/source/utils/config.js
client/src/js/Env.js.example
client/src/js/init.js
client/src/js/oidcProvider.js
docs/_static/css/custom.css
docs/installation-and-setup/envvars.csv

Resolves #666.
- Adds support in the web app for opaque, non-JWT refresh tokens (Azure AD and Okta)
- Adds an envvar (`STIGMAN_CLIENT_SCOPE_PREFIX`) that instructs the web app to add the provided prefix to each scope requested during authentication. This behavior is needed when using Azure AD, which requires each scope be prefixed by `api://<application_id>`.
- Add support to the web app for token responses that do not include a refresh token. Okta will not generate a refresh token unless scope `offline_access` is requested (which can be configured with envvar `STIGMAN_CLIENT_EXTRA_SCOPES = offline_access`)
- API now handles scope claim serializations that are not compliant with [RFC 8693, section 4.2](https://datatracker.ietf.org/doc/html/rfc8693#section-4.2). Okta produces a JSON array …

refactor: token handling for Azure AD and Okta

---

api/source/controllers/Collection.js
api/source/package-lock.json
api/source/package.json
api/source/specification/stig-manager.yaml
client/src/js/SM/Exports.js

Resolves #713
- Adds endpoint `POST /collection/{collectionId}/ckl-archive` which accepts an array of assetId (and optionally benchmarkId) for which to generate CKLs,. The endpoint responds with a stream of `application/zip` once the first CKL is generated and asynchronously appends each subsequent CKL. This preserves a primary design goal of the API to never create/write/delete from the file system, while also offloading ZIP archive construction from the clients.
- Implements an experimental UI interface in the web app that uses the new endpoint. The feature can be used by selecting "Use streaming API (experimental)" from the dialog shown by Collection -> Manage -> Export CKLs...

feat: experimental endpoint/UI for streaming an archive of CKLs 

---

client/src/js/SM/Parsers.js

CKL serializer was failing when parsing CKL with no root XML comment. Added the optional chaining operator.

fix: handle CKL with no root XML comment

---

api/source/controllers/Review.js
api/source/service/mysql/CollectionService.js
api/source/service/mysql/ReviewService.js
api/source/specification/stig-manager.yaml
test/api/postman_collection.json

Return responses in accordance with the OAS definitions for:
- `GET /collections/{collectionId}/review-history`
- `DELETE /collections/{collectionId}/reviews/{assetId}/{ruleId}`

fix: match review/history OAS defintions

---

api/source/controllers/Collection.js
api/source/service/mysql/CollectionService.js
api/source/specification/stig-manager.yaml

OAS definitions and API implementations for endpoints that return information about unreviewed Asset/Rules associated with a Collection. 
- `GET /collection/{collectionId}/unreviewed/assets`, which groups the data by Asset
- `GET /collection/{collectionId}/unreviewed/rules`, which groups the data by Rule
Unreviewed Asset/Rules are those without a Review or having a Review with a result other than `pass`, `fail` or `notapplicable`.
The endpoints are documented as Experimental because comprehensive tests have not been yet written for them.

feat: endpoints that list unreviewed asset/rules

---

api/source/controllers/Asset.js
api/source/controllers/Collection.js
api/source/controllers/Review.js
api/source/controllers/STIG.js
api/source/controllers/User.js
api/source/service/mysql/AssetService.js
api/source/service/mysql/CollectionService.js
api/source/service/mysql/ReviewService.js
api/source/service/mysql/STIGService.js
api/source/service/mysql/UserService.js
api/source/service/mysql/utils.js
api/source/utils/fetchStigs.js
api/source/utils/logger.js

Resolves #670 
For the MySQL services, wraps each multi-statement transaction with a method suitable for use with `async-retry`. The method is  retried if the transaction generates a deadlock error, otherwise the method throws as normal. The retry logic accepts a `statusObj` object which is used to provide the retry count to the output logs.
The `async-retry` options are
```
{
retries: 15,
factor: 1,
minTimeout: 200,
maxTimeout: 200
}
```

feat: retry transactions on deadlock

---

api/source/service/mysql/AssetService.js
test/api/postman_collection.json

Resolves #756
- API: Include `collectionId` in the query that deletes existing records in `stig_asset_map`.
- Tests: Include a `newman` regression test

hotfix: stig-asset update preserves existing mappings

---

docs/the-project/DockerHub_Readme.md

Removes `auth` from the OIDC paths

chore: update compose example for kc 19.0.2

---

client/src/css/dark-mode.css
client/src/js/SM/CollectionGrant.js

- sets transparency for the dark-mode masks
- sets height of the Collection dropdown in the User Properties dialog to 150px, which keeps it entirely in view

fix: dark-mode mask; collection dropdown height

---

client/src/js/review.js

In the Asset/STIG workspace, saving (with or without submitting) an empty `detail` or `comment` generates a PUT request with a `null` value for the field (which the API defines as a request to preserve the existing value). This makes it impossible for users to clear commentary using the workspace.
In the Asset/STIG workspace, saving (with or without submitting) an empty `detail` or `comment` generates a PUT request to the API with an empty string `''` value for the field (which the API applies to update the value). This makes it possible for users to clear commentary using the workspace.

fix: empty commentary removes commentary

---

client/src/js/BufferView.js

Changes to `BufferView.getCalculatedRowHeight()` caused the grid rows to render incorrectly when the page was zoomed out. I reverted to the original implementation, which was still present but commented out. The commented out section did not include an explanation of why the original method was modified and that method is testing fine now.

fix: BufferView renders correctly when zoomed out

---

client/src/js/review.js

When Review->Other Assets was changed to use BufferView, the row expander which displayed commentary fields was removed. This PR provides display of commentary using a floating tooltip that is invoked when hovering over a row.

feat: tooltips in Other Assets grid

---

.github/workflows/build-client.yml
.github/workflows/build-docs.yml
.github/workflows/pub-docker.yml

Updates the external scripts used in the Docker Publish actions so warnings are no longer generated.
Also, updates statements that produce the output of the `prep` step in accordance with [GitHub guidance](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).

chore: update actions to avoid deprecation warnings

---

client/src/js/SM/Metrics.js

The Metrics Report is generating error popups every 30 seconds if the Oldest, Newest or Updated fields show a duration < 1 hour ago. In this situation, the updateData handler is being called with `onlyRefreshView = true`, which skips fetching a value for `apiMetricsCollection`. The uninitialized value is then being passed to the component updaters, which generate errors when trying to access its properties.
This PR adds a closure variable `lastApiMetricsCollection` to hold the last fetched metrics. This value is assigned to `apiMetricsCollection` when `onlyRefreshView = true`

fix: provide last fetched metrics when onlyRefreshView = true

---

client/src/js/SM/ColumnFilters.js

Preserves existing column filters between grid loads.

fix: preserve column filters when a grid loads

---

client/src/js/BufferView.js
client/src/js/SM/Metrics.js

Patches `BufferView` so column renderers are called with the correct scope. The previous implementation broke the `highlighterShim` provided by `SM.ColumnFilters.Renderers` and string filters would not highlight matching characters.
Also reverts a workaround added to the Metrics severity renderer to make it work with unpatched `BufferView`. The workaround is no longer needed.

fix: BufferView calls column renderer with proper scope

---

client/src/js/collectionReview.js

In Collection Review of a STIG, do not wrap the text in `detail` or `comment`. This ensures each row has a consistent height, which is a requirement for `BufferView` to correctly render.

fix: collection review - no column wrap

---

client/src/js/review.js

Saving  a Review with a disabled commentary field produces an illegal request to the API. This PR fixes that by getting all field values, including disabled fields.

fix: include disabled field values

---

client/src/js/SM/CollectionAsset.js

After successfully transferring an asset, the Asset grid fails to reload. This PR fixes that.

fix: transfer assets request uses scoped variable

---

client/src/js/collectionReview.js

The Collection Review tab will allow attempted submission of reviews with a non-compliance result (informational, etc.). This PR adds a test to `isReviewComplete()` that returns false if a selected review has a non-compliance result.

fix: non-compliance result disables submit

---

client/src/js/SM/Parsers.js

Create revision string only if STIG version and Release info supports it. Otherwise null.

Create revision string only if STIG version and Release info supports it.

---

client/src/js/BufferView.js

Modifies `Ext.ux.grid.BufferView` to  cache pre-rendered row innerHTML into a <template> document-fragment for quick assignment to row placeholders in the DOM. This is observed to noticeably reduce lag when scrolling rows.
Also:
- adds support for line clamping for use in future features.
- older source was reformatted for consistency

feat: render rows to a markup cache in BufferView

---

docs/the-project/DockerHub_Readme.md

Updates the sample docker-compose.yml in the Docker Hub read me:
- removes the abandoned envvar `STIGMAN_INIT_IMPORT_SCAP`
- adds the envvars for `STIGMAN_CLIENT_WELCOME_*`

chore: docker-compose file update envvars

---

client/src/js/SM/CollectionGrant.js

Application Management -> User Grants -> Modify User -> Delete Grant button was missing logic and was always disabled. This PR adds the expected functionality and enables the button when a Grant is selected.

fix: logic for grant delete button

---

client/src/js/SM/MainPanel.js

When deployments configure `STIGMAN_CLIENT_WELCOME_IMAGE` with a broken URL, the Welcome widget displays a broken image icon.
This PR modifies the `<img>` tag with an `onerror` handler that ensures the default Navy logo is displayed in this situation.

feat: fallback to navy logo on img error

---

client/src/js/SM/CollectionStig.js
client/src/js/overrides.js

Resolves an issue observed in the wild where the Collection Manage -> STIG grid was not removing its load mask.
- removes a redundant call to reload the grid after an update
- refactors the override to Ext.LodMask which delays the display of the load mask, ensuring that any existing timers are cancelled.

fix: manage stig grid reload

---

client/src/css/stigman.css
client/src/img/logout.svg
client/src/js/SM/NavTree.js
client/src/js/oidcProvider.js

The current logout functionality produces an error in current Keycloak (by sending a non-standard redirect_uri parameter).
This PR fixes that and changes the logout action from a click on the NavTree header to a header tool button.

feat: logout button in navtree header

---

client/src/js/SM/NavTree.js

Resolves #853 
Since the API response is not sorted, perform sort in the client when rendering Assets tree nodes.

fix: sort assets when building tree node

---

api/source/index.js
api/source/package-lock.json
api/source/package.json
api/source/specification/stig-manager.yaml

Updated most dependencies to latest versions.
Code changes to accommodate updates described below:
Updated **Express OpenAPI Validator** to latest version, 5.0.0. This required a subsequent change to a regex string in the API definition, because the EOV update -
- required an updated version of AJV, 
- which now processes regixi as unicode by default (in accordance with JSON schema guidance)
- which invokes strict escape character checking (in accordance with JSON schema guidance)
- meaning escaping ":" is invalid since ':' does not need to be escaped: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Cheatsheet#:~:text=Note%20that%20some,%5Ck.
Updated **js-yaml** to latest version, 4.1.0. Required minor change to index.js because "safeLoad" has been …

chore: Dependency updates

---

client/src/js/overrides.js

Override top-ancestor `initComponent` to normalize the `stateful` property since other framework code invokes 
`if (this.stateful !== false)`

feat: ui stateful property defaults to false

---

api/source/service/mysql/ReviewService.js

Resolves #873 
Escapes the values of the session variables in the query `sqlVariables`.

fix: escape values of session variables

---

client/src/js/collectionReview.js

Adds UI validation in the Reject Reviews dialog for the maximum length of the status text, which is currently 255 characters.

feat: validate max length for status text

---

client/src/js/SM/ReviewsImport.js
client/src/js/SM/TipContent.js
docs/user-guide/user-guide.rst

fix: changed review status import option label from "Null" to "Keep Existing" for better clarity. Updated tooltip and docs as well.

fix: changed review status import option label from "Null" to "Keep Existing" for better clarity.

---

client/src/js/SM/ReviewsImport.js

Resolves #880 
In the Review import code, normalizes the cklWebDb* property values to lowercase when attempting to match an existing Asset.

fix: case insensitive matching of CKL asset

---

api/source/utils/config.js

chore: stigs and checklists keep getting bigger. Changed STIGMAN_API_MAX_JSON_BODY default value from 5mb to 10mb. 
Resolves: #628

chore: stigs and checklists keep getting bigger. Changed STIGMAN_API_MAX_JSON_BODY default value from 5mb to 10mb. 

---

api/source/package-lock.json
api/source/package.json
api/source/utils/auth.js
api/source/utils/fetchStigs.js

latest got is offered as an ESM only
resolves same issue as dependabot PR #923 
Regenerated package-lock with updates.

chore: Update got to latest version, use dynamic import

---

api/source/service/mysql/migrations/0019.js

We've decided to abandon the approach that requires a `ccId` column in the `rule` table. Therefore, migration 0019 can be simplified by removing the queries that insert values into the column. The column itself is planned for removal in migration 0020.

refactor: remove rule.ccId instantiation from migration 0019

---

client/src/js/SM/Parsers.js

Resolves: #890
This code successfully processes the sanitized sample files from ACAS and HBSS which were provided with #890. We need additional feedback from the community to establish we can handle all of the real-world XCCDF from those tools.
This PR handles the non-standard value for `<TestResult test-system>` that is seen in the HBSS file. According to [the XCCDF specification](https://csrc.nist.gov/CSRC/media/Publications/nistir/7275/rev-4/final/documents/nistir-7275r4_updated-march-2012_clean.pdf) the `test-system` attribute "SHOULD be either a CPE name or a CPE applicability language expression", but HBSS does not follow this suggestion and our existing code expected a CPE name.
Unlike SCC and OpenSCAP, neither ACAS nor HBSS  provide a timestamp for each `<rule-result>`. I've …

feat: parse and import XCCDF with root-level TestResult

---

api/source/package-lock.json
api/source/package.json
release-notes.rst

1.3.1
-----
Changes:
- (App/API) Allow users to replace existing STIG Revisions when importing reference benchmarks.
- (App) Restrict Collections Managers from creating or altering Owner Grants. (#934)
- (App) Parse and import XCCDF with root-level TestResult element (Found in SCAP scan results performed by HBSS or ACAS).
- (App/API) Support for importing known forms of non-DISA STIGs (vmWare STIG Readiness Guides).
- (App) Made grid text selectable in most places.
- (API) Added granular STIG Severity counts to metrics. (#915)
- (API) Include controls associated with CCIs in CCI projection responses. 
- (API) Updated dependencies identified as vulnerable by Dependabot. (#925) (#918)
- (Docs) Various updates to documentation describing feature and behavior changes.
- (API) Removed …

chore: release updates

---

.readthedocs.yml

readTheDocs latest fails to generate pdfs, resulting in entire build failure.
Removing pdf generation.

docs: disable pdf generation, remove deprecated python version

---

client/src/js/overrides.js

Restore XSS protection that was inadvertently commented out in commit fa6249e61923f707e33c9b29117c3010d0b5323d

hotfix: restore commented out code

---

client/src/js/SM/Library.js
client/src/js/SM/TipContent.js

The STIG compare feature only shows differences when the `ruleId` associated with a `STIGId` has changed between revisions. We discovered cases when `ruleId` is not changed but other properties, such as the check content, have changed. This PR modifies the feature to show these differences.

feat: show stig diff even when ruleId is unchanged

---

api/source/service/mysql/migrations/0020.js

Modifies `insert` query to `insert ignore` to accommodate unexpected duplicate digests

hotfix: insert ignore into check_content

---

api/source/service/mysql/migrations/0019.js
api/source/service/mysql/migrations/0021.js

Resolves: #959
This resolves the display of incorrect metrics in the web app.
Patches migration 0019 to correctly populate table `current_rev`. Adds the patch statements to a new migration (0021) to ensure the correction is applied to deployments which already executed migration 0019.

fix: current_rev fix in 0019 and 0021

---

.dockerignore

Modified `.dockerignore` to permit the client `node_modules` directory to be in the build context

fix: include client node_modules in container builds

---

client/src/css/init.css
client/src/img/external-link.svg
client/src/js/init.js

Halts execution of the web app early in `init.js` when `window.isSecureContext === false` and provides an error message with details.

feat: check window.isSecureContext before loading

---

api/source/service/mysql/MetricsService.js
api/source/specification/stig-manager.yaml
client/src/js/SM/CollectionPanel.js

- (OAS/API) Adds the `title` property to Metric responses that include STIG data (benchmarkId, revisionStr)
- (UI) Adds a column for STIG title to grids populated from Metric endpoints. Affects grids in the Collection dashboard and Collection Management workspace. The column is initially hidden by default.

feat: STIG title column, hidden by default

---

client/src/css/stigman.css
client/src/img/copy.svg
client/src/js/SM/CollectionPanel.js
client/src/js/SM/Global.js
client/src/js/overrides.js

Reverts fa6249e
Reverts PR #921 
Adds a context menu to all grid cells with menu items to
- copy the cell's value to the clipboard
- copy the CSV representation of the cell's row to the clipboard

feat: grid context-menu for clipboard copy

---

docs/build.sh

A recent change to the sphinx image broke our docs build script.
Changed build script to specify tag of last known version that worked for us, instead of implied "latest".

pin sphinx container tag

---

client/src/js/SM/Assignments.js
client/src/js/collectionAdmin.js

Removes the non-compliant elevate parameter from requests made during User Grant assignments.
Fixed regression preventing app management interface from updating Collections.

fix: remove non-compliant elevate parameter, fix regression preventing app management interface from updating Collections

---

client/src/js/SM/WhatsNew.js

Ensure new items are displayed. Before string comparisons, splits the value stored in localStorage by hyphen and pads the month and day with zero as needed before re-combining.

hotfix: workaround non-standard what's new dates

---

api/source/service/mysql/migrations/0026.js

Renames the column `isCloning` to `isNameUnavailable` and sets the generated value to 1 if the `state` value is either `enabled` or `cloning`. The unique index `index3` which was attached to `isCloning` comes along for the ride and now works as intended.

fix: duplicate collection name detection

---

client/src/js/collectionReview.js

Resolves #1104 
Calls to the API from the Collection review workspace in the web app now specify the ruleId from displayed checklist.

fix: collection review calls endpoints with displayed ruleId

---

client/src/js/SM/Inventory.js

Resolves #1114 
Web app Inventory->Export:
The `csvFields.delimiter` property of the STIG and Asset checkboxes is now set from localStorage instead of being hardcoded.

fix: initialize delimiter value from localStorage

---

client/src/img/color-picker.svg

Resolves #1113 
The fill color of `color-picker.svg` is now set to 50% black instead of 74% black

fix: use 50% black fill in color-picker.svg

---

.github/workflows/api-container-tests.yml

Resolves: https://github.com/NUWCDIVNPT/stig-manager/issues/1107
The updated workflow now tests both of our API containers across multiple MySQL versions (8.0.32, 8.0.33, 8.0.34). This now uses a matrix strategy.

Test both delivered containers against supported MySQL versions

---

.github/workflows/api-audit-test-coverage-response.yml
.github/workflows/client-sonarcloud.yml

Resolves: https://github.com/NUWCDIVNPT/stig-manager/issues/1101
This PR introduces:
Sonar Cloud Integration: We're now connecting to the Sonar Cloud organization NUWCDIVNPT. This integration will facilitate code quality checks and monitoring, enhancing our CI/CD pipeline.
The workflow has been configured to analyze and monitor the code quality for the API and Client separately.
Action Required:
For this to work, someone with elevated permissions will need to enter the proper Sonar cloud secret tokens which can be accessed through me or https://sonarcloud.io/organizations/nuwcdivnpt/projects?sort=name

feat: Implement API/Client Sonarcloud GitHub Action

---

api/source/controllers/Review.js
api/source/service/mysql/ReviewService.js
test/api/postman_collection.json

Resolves #1098 
Resolves #985
Refactors the controller and MySQL service methods for Asset Review POST, PUT, and PATCH endpoints:
`POST /collections/{collectionId}/reviews/{assetId}`
`PATCH /collections/{collectionId}/reviews/{assetId}/{ruleId}`
`PUT /collections/{collectionId}/reviews/{assetId}/{ruleId}`
The revised approach performs most request validation logic in the MySQL service.

refactor: post/put/patch asset reviews

---

client/src/css/dark-mode.css
client/src/css/stigman.css
client/src/img/remove.svg
client/src/img/trash.svg
client/src/js/SM/CollectionClone.js
client/src/js/SM/CollectionForm.js
client/src/js/SM/CollectionStig.js
client/src/js/collectionManager.js
client/src/js/overrides.js
client/src/js/stigman.js

Resolves #1127 
- Redesign of the Collection Manage interface.
- Override of the Ext.Element method `addStyles` which sums border widths during sizing calculations. Use `parseFloat()` instead of `parseInt()` to account for when the browser uses fractional scaling.

fix: ui scaling preserves element borders

---

api/source/controllers/Asset.js
api/source/controllers/Collection.js
api/source/utils/escape.js
client/src/js/SM/Exports.js
client/src/js/review.js
test/api/postman_collection.json

fix: escape special characters in filenames

---

client/src/js/SM/Parsers.js

fix: #1155 resultStats object was declared once and reused for every iSTIG element, causing stats to be cumulative for multi-stig .ckls

---

api/source/utils/auth.js
api/source/utils/config.js
api/source/utils/error.js

Keycloak was previously using `clientId` but now uses `client_id` which conforms w/ oidc spec. This caused our fallback service name to fail with new versions of Keycloak. When service name is not specified, app will now fall back through azp, client_id, and clientId claims. 
Changed processing to throw a privilege error If no username can be resolved from token claims. 
Added an "Authorize Error" object to SmError that returns status 401.

fix: Change STIGMAN_JWT_SERVICENAME_CLAIM to conform w/ standard. Don't create null user if no username claim found.

---

api/source/index.js
api/source/service/utils.js

sslconfig needs to look only one level up instead of two for certs after service folder restructuring

---

.readthedocs.yml
docs/conf.py

readTheDocs build now fails if build.os is not specified

chore: readTheDocs changes

---

api/source/controllers/Asset.js
api/source/service/AssetService.js
api/source/specification/stig-manager.yaml
client/src/js/SM/CollectionAsset.js
test/api/postman_collection.json

Resolves #1209 
- In the API, introduces the endpoint `PATCH /assets` to support batch operations on Assets. This initial implementation supports batch deletes only.
- In the web app, calls this new endpoint when deleting Assets from the Collection Manage workspace.
Benchmarks, delete 2000 Assets:
Legacy approach: 2000 API calls @ ~125ms each (250s) with 3 database writes each (6000)
New approach: 1 API call @ ~175ms with 3 database writes total

feat: multi-asset patch with delete support

---

api/source/service/AssetService.js
api/source/specification/stig-manager.yaml
client/src/css/stigman.css
client/src/js/SM/Review.js
client/src/js/collectionReview.js
client/src/js/review.js

- Adds timestamp values (`ts`, `statusTs` and `touchTs`) to the response body of `GET /assets/{assetId}/checklists/{benchmarkId}/{revisionStr}` when the `format` query parameter is `json`
- Adds a grid column that displays `touchTs` in the Asset/STIG workspace for
- the Checklist grid
- the Other Assets grid
- Adds a grid column that displays `touchTs` in the Collection/STIG workspace's Reviews grid
- The grid columns are sortable but not filterable

feat: display touchTs in grids for checklist, other assets, and reviews

---

client/src/js/collectionReview.js

resolves #1111 
This PR introduces enhancements to the feedback logic when setting reject status. The component now only allows a rejection to be submitted when the text area contains > 0 characters.

Enhancement: Setting Reject status will now require text before rejecting. 

---

.github/workflows/api-container-tests.yml

MySQL released version 8.0.36 on 2024-01-16
We could automate the lookup of the last three 8.0.x releases. A possible command is:
```
docker run --rm quay.io/skopeo/stable list-tags docker://docker.io/library/mysql | \
jq -r '.Tags[]|select(test("^8\\.0\\.\\d+$"))' | \
sort -V | \
tail -n3 | \
jq -Rnc '[inputs]'
```

chore: update MySQL recent versions in api-container-tests.yml

---

.github/workflows/api-audit-test-coverage-response.yml
.github/workflows/api-container-tests.yml
.github/workflows/build-binary-artifacts.yml
.github/workflows/build-client.yml
.github/workflows/build-docs.yml
.github/workflows/client-sonarcloud.yml
.github/workflows/pub-docker.yml

This pull request upgrades the Node.js version for actions within this repository to use Node.js 20.
The following actions were changed to version 4:
actions/checkout
actions/upload-artifact
actions/setup-node
actions/download-artifact
actions/github-script

Chore: Update to node 20 based workflow actions

---

.github/workflows/api-container-tests.yml

This PR adds a new job to dynamically fetch the three latest MySQL version tags from Docker Hub and utilize them for container testing. This PR also incorporates our project's minimum required MySQL version, 8.0.21, into the testing matrix.

CI/CD: Enhance workflow with automatic MySQL version testing

---

client/src/css/stigman.css
client/src/js/SM/CollectionAsset.js
client/src/js/SM/CollectionPanel.js
client/src/js/SM/ReviewsImport.js
client/src/js/SM/TipContent.js

Resolves #1045 
Adds a button to the Collection-level dashboard that exposes the CKL(B)/SCAP import feature to all users. This description of the feature may be modified as the PR is refined.

feat: add import results to collection dashboard

---

client/src/js/SM/Review.js

This PR fixes a bug that was triggered when review evaluation fields contained Windows line endings. The `lastSavedData` for these fields was being initialized from the field component's `[Component].value` property, but the `reviewChanged()` function implemented [here](https://github.com/NUWCDIVNPT/stig-manager/blob/a106046491f0b75df294672e883f7d451fb1bdf5/client/src/js/SM/Review.js#L303-L310) was comparing that data to the DOM-normalized values returned by `[Component].getValue()`.
The corrected code initializes `lastSavedData` by calling `[Component].getValue()` on these fields.

fix: get lastSavedData from dom

---

docs/installation-and-setup/data-and-permissions.rst

This fix corrects the path to an image which points to our ERD diagram 'eer-stigman-wide.svg'.

Hotfix: Correct path to eer-stigman-wide.svg in the rst.

---

client/src/js/SM/Review.js

This PR corrects the way `resultEngine` values are handled in the Asset/STIG Review workspace when dragging a Review from Other Assets into the Review Form. 
Existing code did not trigger the Result combobox `select()` handler, which updates the resultEngine sprite  when `result` is changed. The fixed code explicitly fires the `select` event.
Also, the `resultChanged()` function was updated to check for a change of `result` instead of a change of `resultEngine`.

fix: dragged review sets engine value

---

api/source/package-lock.json
api/source/package.json
release-notes.rst

1.4.5
-----
Changes:
- (UI/API) feat: Status text field expanded to 511 characters.
- (UI) bugfix: Review `resultEngine` no longer keeps old value when using drag & drop from Other Assets. 
- (API/DB) chore: Remove unused current_group_rule table and view. 
- (API) bugfix: Review `resultEngine` now only set to null when PATCH'd with a `result` and no `resultEngine`.
- (API) feat: DB bootstrap improvements, build script, static data.
- (API) chore: Update dependency in response to CVE-2022-25881
- **Includes database migration**

chore: updates for 1.4.5

---

api/source/controllers/Asset.js
test/api/form-data-files/appdata.json
test/api/postman_collection.json

This PR extends on PR #1270 
The following functions no longer require an access level >= manage in order to retrieve asset metadata. They now will only require an access level of restricted. 
- getAssetMetadata
- getAssetMetadataKeys
- getAssetMetadataValue
Tests under postman collection `STIGMan OSS / GETs / Asset GET / {asset Id} / metadata` were altered to account for these new access level rules. Some of the test data and assertions were altered also.

Refactor: gets to asset metadata  no longer require grant >= manage

---

api/source/service/CollectionService.js
test/api/postman_collection.json

This PR adds code to the handler for `PUT /collections/{collectionId}/grants/{userId}/access` that silently ignores items in the request body whose `assetId` is not associated with `collectionId`, or if the asset is not enabled.

fix: put asset/stigs ignores assets not enabled in collection

---

client/build.sh
client/src/js/SM/Exports.js

Resolves #1310 
This PR refactors `client/src/js/SM/Exports.js` and removes a `with (Math)` block because that is now forbidden in strict mode. This block is causing the most recent version of `uglify.js` to throw during the client build stage of the Docker publish action. Which results in an incomplete client directory in our images.
This error during client build is not aborting the build script, which would have aborted the publish action. So I've added `set -e` to the top of the build script to remedy this.

fix: remove `with (Math)` block in `Exports.js`

---

api/source/controllers/Asset.js
api/source/controllers/Collection.js
api/source/utils/escape.js
api/source/utils/writer.js
client/src/js/ExportButton.js
client/src/js/SM/CollectionPanel.js
client/src/js/SM/Global.js
client/src/js/SM/MetaPanel.js
client/src/js/appDataAdmin.js
test/api/postman_collection.json

Resolves #1307 
This PR modifies the API and web app to add a time string to the default filenames presented by a browser when downloading files. The time string value is an ISO8601-like token with the format `YYYY-MM-DDThhmmZ`.
The date string is appended to the following downloads:
- ZIP archives of CKL, CKLB, and XCCDF checklists
- Individual Asset/STIG checklists in CKL, CKLB, or XCCDF formats
- Collection and Meta-collection metrics, JSON and CSV
- Individual grid CSV
In addition, the filename escape routine in the API was ported to the web app.

feat: time string appended to attachment filenames

---

api/source/service/migrations/sql/current/10-stigman-tables.sql
api/source/service/migrations/sql/generateSchema.sh

Removed `DEFINER=....` lines from 10-stigman-tables.sql
Added sed expression to generateSchema to remove definer lines when generating the file
resolves: #1317

fix: remove DEFINER statements from output of `generateSchema.sh`

---

api/source/controllers/Collection.js
api/source/service/ReviewService.js
api/source/service/migrations/0033.js
api/source/specification/stig-manager.yaml
client/src/js/SM/CollectionForm.js

feat: Remove unlimited history records option, set new cap to 15, new default value to 5

---

api/source/service/STIGService.js
test/api/postman_collection.json

When STIG Revision is removed and default_rev is affected, recalculate stats and update default_rev table from view.
Resolves: #1321

fix: recalculate stats and update defualt_rev table from view whenever default_rev is affected by STIG Revision deletion

---

api/source/service/OperationService.js
api/source/utils/config.js
api/source/utils/logger.js

Resolves: #799 
Adds operational stat tracking to logger, building an object to represent:
- total requests (including static content)
- total API endpoint requests
- total request processing duration
- Broken out by operationId:
- count
- avgDuration
- minDuration
- maxDuration
- maxDuration update count
- request counts for unique clients (clientIds anonymized)
- projections used in requests
- count
- minDuration
- maxDuration
- durationTotal
- durationAvg
Added Dev envvars to control adding operational stats to log entries and obfuscating clientIds.
Moved existing `durationMs` and `retries` properties to new `operationalStats` object in log.
Details added to Anonymized Deployment Details:
- Building Collection stats from metrics table, including overall Asset, rule, review counts for …

feat: enhanced app deployment details report, added operation stats tracking to logger

---

client/src/js/SM/Cache.js
client/src/js/SM/CollectionPanel.js
client/src/js/collectionAdmin.js
client/src/js/collectionManager.js

Resolves #1326 
This PR refactors the web app to eliminate the unneeded and non-performant `projection=labels` parameter from the initial request for all Collections. In individual Collection workspaces, calls have been inserted that refresh that Collection's label cache from the just retrieved data.
Also, added logic to the Collection dashboard that suppresses three repetitive requests to the Metrics endpoints when the dashboard is first loaded. There was no issue for this, but the behavior was noted during other development efforts.

refactor: remove web app request for labels projection

---

api/source/controllers/STIG.js
client/src/js/SM/StigRevision.js

Resolves #1342 by adding `elevate=true` to the web app code for importing new benchmarks.
This PR also refactors the STIG import handler code in the API so it does not continue execution after detecting an unelevated request.

fix: elevate handling for stig import

---

.github/workflows/api-audit-test-coverage-response.yml
.github/workflows/client-sonarcloud.yml

This pull request implements a condition to skip  SonarCloud analysis when a pull request is opened from a forked repository. This will avoid "failed" workflows in the future.

Enhancement: skips sonarcloud actions when PR form fork

---

api/source/controllers/STIG.js
api/source/controllers/User.js

getStigById/getUserByUserId were returning a empty 200 response body when querying a resource that does not exist. This was found through the validation response workflow. This PR alters these endpoints to now return a 404.

fix: getStigById/getUserByUserId now return 404 when querying a resource that does not exist.

---

api/source/service/AssetService.js
api/source/service/CollectionService.js
api/source/service/ReviewService.js

Resolves #1357 
The PR changes the argument passed to `pair.split()` as recommended in the issue. 
```javascript
const [key, value] = pair.split(/:(.*)/s)
````

fix: metadata query param parsing

---

api/source/service/CollectionService.js

When calling queryCollections w/ a collectionId, pass it to getCollectionLabels (instead of "all") to limit label query
resolves: #1361

fix: pass collectionId to getCollectionLabels() when known

---

api/source/controllers/Asset.js
api/source/service/AssetService.js
api/source/specification/stig-manager.yaml

Resolves: #1370 
This PR updates the following functions to implement transaction handling:
- removeStigsFromAsset
- removeStigFromAsset
- deleteAsset
- deleteAssets
Also, attachAssetsToStig was edited to call pruneCollectionRevMap prior to updateDefaultRev.
note: removeStigsFromAsset will never return data as it is. If we want to return the stigs deleted the call to queryStigsByAsset should be made before stig_asset_map deleting occurs.

fix: Update functions to use transactions

---

api/source/service/STIGService.js

Support for importing Benchmarks with duplicate CCI reference elements, as discussed in #1412.

feat: handle duplicate CCI reference elements in benchmark rules

---

client/src/js/overrides.js

Improves the local ExtJS override that addresses fractional scaling issues in the browser. Rounds any floating point value to an integer. This fixes border clipping issues seen in current and new development code.

fix: ensure integer size when fractional scaling

---

api/source/service/AssetService.js
client/src/js/modules/package-lock.json
client/src/js/modules/package.json

minor changes to XCCDF generation to pass NIST XCCDF validation, added cdf: namespace prefix to elements so they import into STIG Viewer
stig-manager-client-modules 1.4.3 brings support for Eval-STIG style XCCDF files
Resolves: #1411

XCCDF exports pass NIST validation, update stig-manager-client-modules to 1.4.3

---

client/src/js/init.js
client/src/js/modules/oidcProvider.js
client/src/js/stigman.js

Resolves #1447 
`init.js` and `stigman.js` were updated to display concatenated status messages during the bootstrap phases 1) authorization, 2) app loading, and 3) initial API request for `/user`.
`OIDCProvider.js` was updated to throw on errors from the `token` endpoint. Also, the stored PKCE code verifier is now removed after being used for the token request. Before making the token request, OIDCProvider now checks if the stored code verifier exists. If not, it restarts the authorization phase by redirecting back to the base URL.
These updates appear to handle the scenario where a user has bookmarked our authorization request while viewing the OP login page, and later uses this bookmark.
Handling of the API request to `/user` was not modified, it uses our common routine for making API …

feat: detailed status during web app bootstrap; handle token errors

---

client/src/js/modules/oidcProvider.js
client/src/js/stigman.js

In `oidcProvider.js`:
- when redirecting to the OP authorization endpoint, store the `state` value we generated along with the PKCE code challenge we sent and the associated code verifier. 
- when processing the OP's redirected authorization code response, test whether the OP `state` matches our last stored `state`. If it does, continue with a token request using the stored code verifier. If it does not, display an error and offer to restart the authorization flow.
- If the token request fails, display a textarea with context details including the saved PKCE data, the full authorization request, the OP's authorization code redirect URL, and the full token request body.
This might help in debugging esoteric issues as reported in #1440. The PKCE values can be found using DevTools or a JS …

feat: test oidc state before token request

---

client/src/js/collectionReview.js
client/src/js/review.js

Resolves the bug discussed in #1463 
Replace spaces in benchmarkId with `_` when using it as an identifier that becomes part of class name string.

fix: handle spaces in benchmarkId when used in class name

---

api/launchers/stig-manager.bat
api/launchers/stig-manager.sh
api/pkg.config.json

- Bumps the Node version used for the binaries to v18.
- Adds the POA&M XLSX templates to the static items in `pkg.config.json`
- Updates the Batch and Shell scripts to include recently added environment variables.

fix: api binary build

---

.github/workflows/build-binary-artifacts.yml

This PR adds `workflow_call` as a trigger to `build-binary-artifacts.yml`. This makes it callable from other workflows.

feat: add workflow_call to build-binary-artifacts.yml

---

.github/workflows/api-binary-tests.yml
.github/workflows/build-binary-artifacts.yml

This PR adds a github workflow to build stig-manager artifacts and run mocha api tests on the linux binary.

feat: adds workflow to run mocha tests on linux binary artifact

---

api/source/index.js
api/source/utils/auth.js
api/source/utils/error.js

Resolves #1482 
The existing `verifyRequest()` does too much work for a utility function (non-middleware) attached to EOV:
- validates tokens
- creates the request's userObject property
- creates/updates a user's lastClaims
- checks for improper use of the parameter `elevate=true`
- checks scopes for the request
This PR separates these tasks into two new Express middlewares and limits the renamed EOV utility function to checking scopes.
As far as handling OP outages, the current code actually does a fair job with that. There are three scenarios to handle:
1. OP host is gone (connection requests are ignored)
2. OP host is up but OP service is down (connection requests are actively refused by host OS)
3. OP host and service are up but are slow or unresponsive (connections accepted but …

refactor: verifyRequest => validateOauthSecurity

---

api/source/specification/stig-manager.yaml

To match the API response, adds the `ruleIds` property to ReviewAssetRuleRead.
Changes `ruleId` references from `String255` => `RuleId`. 
This PR keeps `RuleId` as a ref to `String45Nullable`, but I questioned whether that should change to `String45` and there be a separate `RuleIdNullable` that uses `String45Nullable`. But that means sorting out where ruleId might be null, and that's beyond what this PR was for.

fix: add ruleIds to ReviewAssetRuleRead; remove String255 references

---

client/src/js/SM/User.js

resolves #1512 
This pr resolves a bug which would cause the client to throw.
Changes include:
1.  Adding the userGroups projection when patching a user. (this is where we were throwing) 
2. Patching the unregistered users userGroups to remove ALL of its grants.

fix: Error as a result of unregistering a user

---

api/source/index.js
api/source/service/CollectionService.js
api/source/service/OperationService.js
api/source/service/UserService.js
api/source/utils/auth.js
api/source/utils/config.js
client/src/js/SM/User.js
docs/installation-and-setup/envvars.csv

Resolves #1515 
- (API) Formats `config.oauth.claims.privileges` to conform to MySQL JSON path syntax by double-quoting all object properties.
- (API) Updates queries that consume `config.oauth.claims.privileges` to surround the path statement with single-quotes in order to support the double-quoted path components
- (API) Renames function `formatChain()` to `formatJsChain()` for clarity
- (API) Renames properties of `config.oauth.claims` for clarity: 
- `privileges` => `privilegesChain`
- `privilegesPath` => `privileges`
- (API) Removes `oauth.claims` from `Env.js` served to the web app since it is no longer used by any web app code
- (API) Adds a missing `const` declaration in `User.js`
- (API) Replaces hardcoded path `$.name` with `$.${config.oauth.claims.name}` in …

fix: handling of user-defined jwt claims

---

api/launchers/stig-manager.bat
api/launchers/stig-manager.sh
api/source/controllers/User.js
api/source/index.js
api/source/service/UserService.js
api/source/specification/stig-manager.yaml
api/source/utils/config.js
api/source/utils/log-schema.json
client/build.sh
client/src/css/dark-mode.css
client/src/css/stigman.css
client/src/js/SM/FlexboxLayout.js
client/src/js/SM/MainPanel.js
client/src/js/resources.js
client/src/js/stigman.js
docs/installation-and-setup/envvars.csv
test/api/mocha/data/user/user.test.js

resolves #1451 
resolves #418 
API: 
1. _getUsers_ operation ID gained a query param of _'privilege'_ whos values can be _["admin" , "create_collection"]_. This will return users with the specified privilege.
Client
1. Adds an env var to control the display of app managers on the home page  "_STIGMAN_CLIENT_DISPLAY_APPMANAGERS_"
2. Adds card on home screen that lists display names and emails of users with _"admin"_ privilege.
3. Additionally adds new css which allows for the new card aswell as the "Welcome" card to be scrollable when content overflows.

feat: adds users with admin privileges to home screen

---

.github/workflows/api-binary-tests.yml

This pr alters the api-binary-tests workflow so that it triggers when there are changes to the scripts involved with building binaries.
This ensures that any modifications to the binary build scripts are validated by Mocha tests, confirming the accuracy of the Linux binary's API.
Should be merged before #1528

feat: now runs when changes are made to scripts involved with building binaries.

---

api/build.sh
api/pkg.config.json

resolves #1176 
resolves #1501 
The original PKG was deprecated so this pr replaces pkg with a maintained fork named "@yao-pkg/pkg". 
We now can support building binaries on latest node version.

Feat: Replaces pkg with a maintained pkg fork ''@yao-pkg/pkg"

---

api/source/service/STIGService.js
api/source/specification/stig-manager.yaml
test/api/mocha/data/stig/stigs.test.js
test/api/mocha/referenceData.js

resolves #1509
This PR introduced two new projections [`"stigs", "ruleIds"]` to GET `/stigs/rules/{ruleId} `
Schema:
- getRuleByRuleId now accepts two new projections [`"stigs", "ruleIds"]`
- getRuleByRuleId's response can now optionally include a ruleIds array and stigs array
API:
- Code was added to handle two new projections [`"stigs", "ruleIds"]`
Tests:
- Test were added to ensure correct functionality

feat: getRuleByRuleId returns clone rules and revisions related to ruleId

---

api/source/bootstrap/docs.js
test/api/mocha/data/operation/op.test.js

checks that endpoint responds with correct portion of api definition when provided with jsonPath param

Added test for op/definition with jsonPath param

---

client/src/js/collectionAdmin.js

This PR fixes a bug where the Collection Properties panel for Application Management -> Collections is not being displayed.

fix: display the collection properties panel in app manage

---

api/source/controllers/Asset.js
api/source/controllers/Collection.js
api/source/controllers/Metrics.js
api/source/controllers/Review.js
api/source/service/CollectionService.js
test/api/mocha/data/collection/collectionGet.test.js

resolves #1364 
This pr correctly adds proper error handling when `getCollectionInfoAndCheckPermission` is called with elevate=true. 
Changes:
- Adds new function to Collection Service `doesCollectionExist` which will query the database for a collectionId to ensure it exists 
- `getCollectionInfoAndCheckPermission` now calls `doesCollectionExist` when envoked with elevate=true. 
- Makes `getCollectionInfoAndCheckPermission` async 
- Adds await to calls to `getCollectionInfoAndCheckPermission`
- Adds a test to confirm functionality.

fix: adds checking if a collection exists when elevated in getCollectionInfoAndCheckPermission

---

.github/workflows/api-state-tests.yml
api/launchers/stig-manager.bat
api/launchers/stig-manager.sh
api/source/bootstrap/dependencies.js
api/source/bootstrap/middlewares.js
api/source/bootstrap/server.js
api/source/bootstrap/signals.js
api/source/controllers/Operation.js
api/source/index.js
api/source/service/utils.js
api/source/specification/stig-manager.yaml
api/source/utils/auth.js
api/source/utils/config.js
api/source/utils/state.js
docs/installation-and-setup/envvars.csv
test/state/mocha/bootstrap.test.js
test/state/mocha/lib.js
test/state/package-lock.json
test/state/package.json

Resolves #1503 
- supports API state concepts with an instance of a `State` class which extends `EventEmitter`
- refactors bootstrap code to use the `State` instance
- consolidates dispersed calls to `process.exit()` into a single `statechanged` handler
- moves signal handling code from the database utilities to a dedicated signal handling module
- introduces the envvar `STIGMAN_DEPENDENCY_RETRIES` to configure retries of the dependencies during startup
- introduces the unauthenticated endpoint `GET /op/state`
- introduces a testing framework and workflow for operations affecting state

feat: state module

---

test/api/runMocha.sh

script when ran with coverage was calling state tests which ultimately causes failures. Is now only scopes to e2e api tests.

fix: only let coverage script run on e2e api tests

---

api/source/controllers/Asset.js
api/source/service/utils.js
api/source/specification/stig-manager.yaml
test/api/mocha/data/asset/assetPost.test.js

Part of issue 1533
Behavior with dryRun=true:
- Runs validation check only, without creating assets.
- Returns 204 if validation passes.
- Returns 422 Unprocessable Entity if validation fails with the validation errors.
Behavior without dryRun (as it was before):
- Runs validation and proceeds with asset creation.
- Returns 201 Created on success or 422 Unprocessable Entity on validation failure with validation errors.

feat: adds dry run to batch asset creation

---

client/src/js/SM/ColumnFilters.js

Resolves #1570 
This PR modifies the `handleHdDown` override in `client/src/js/SM/ColumnFilters.js`, which is responsible for displaying a column filter menu when a grid header is clicked. A more expansive condition was added that displays the menu if the target **or it's parent element** contains the ExtJS class `x-grid3-hd-inner`. This results in the filter menu being shown more reliably.

fix: show filter menu on click of nested header elements

---

api/source/bootstrap/client.js
api/source/utils/config.js
client/src/js/modules/oidcProvider.js
docs/installation-and-setup/envvars.csv

Resolves #1580 
This PR introduces support for configuration of the Oauth2 `response_mode` requested by the web app when initiating the Authorization Code Flow with PKCE. Current behavior is to always request `response_mode=fragment`.
`api/source/utils/config.js` was modified to support a new environment variable `STIGMAN_CLIENT_RESPONSE_MODE` which can take the values `query` or `fragment` with a default of `fragment`. I went with `fragment` as the default to ensure backwards compatibility and because there may be a marginal security benefit. Fragments are not logged by many proxies and Chrome Dev Tools suppresses the fragment from HAR files.
`api/source/bootstrap/client.js` was modified to add `STIGMAN.Env.oauth.responseMode` to the dynamically generated `js/Env.js`, with the value …

feat: envvar for client OAuth2 response_mode

---

client/src/js/modules/package-lock.json
client/src/js/modules/package.json

no longer requires ckl/b element releaseInfo

deps: Update client modules to 1.5.1

---

client/src/js/SM/Manage.js

resolves:  #1581 
This PR fixes a bug that would allow a label of the same name but different case to be created in the UI.
The code now compares incoming labels and existing labels in all lowercase.

fix: Duplicate labels of different case can no longer be created.

---

api/source/specification/stig-manager.yaml

This PR does not resolve an issue. 
Fixes incorrect OAS.

fix: corrects asset batch create 422 response

---

client/src/js/SM/NavTree.js

This PR has no issue. 
This PR fixes an issue where the gear icon to open the collection management screen would disappear after updating a collection.
To reproduce, open a collection management tab and alter a collection setting such as max reviews history. Notice the gear icon in the nav tree disappear. 
This PR prevents that the gear icon from disappearing.

fix: Fixes disappearing gear icon after modifying collection.

---

client/src/js/SM/AppInfo.js

Resolves #1603 
Add optional chaining to existing statements to handle data with no Groups, Users and/or Collections.

fix: use optional chaining in generateSharable

---

api/source/controllers/Asset.js
api/source/specification/stig-manager.yaml
client/src/js/SM/Manage.js
test/api/mocha/data/asset/assetPost.test.js

resolves #1609 
This PR alters the 422 response of a createAssets dry run failure to a 200.

refactor: createAssets dry run failure now returns 200.

---

client/src/js/SM/Manage.js

Attempting to create a duplicate asset in a collection now gracefully handles the error returned by the API. This functionality was broken when createAsset was altered during #1567.

fix: correctly handles new response for duplicate asset name

---

api/source/bootstrap/client.js

Resolves an issue where setting STIGMAN_CLIENT_STRICT_PKCE to `false` does not have the intended effect in the web app.
In `api/source/bootstrap/client.js`, needed to remove the double quotes around the .toString() value of `config.client.strictPkce`.

fix: assign STIGMAN.oauth.strictPkce to boolean

---

client/src/js/oidcWorker.js

Handle scopeValue that is either an array or space-separated string.
Remove hard-coded openid scope from token request.

Handle scopeValue that is either an array or space-separated string

---

client/src/js/oidcWorker.js

removed stig-manager:op from requiredUserScopes
re-added "openid" to scope request to conform with oidc authorization code flow standard

remove :op from required user scopes; handle array in aud claim; re-added "openid" to requested scopes 

---

docs/the-project/DockerHub_Readme.md

Default values were found to be too small when generating .ckl file for RHEL_9 with large comments. 
Sets MySQL values to: --innodb-buffer-pool-size=1024M --sort_buffer_size=16M

specify larger sort_buffer_size and innodb-buffer-pool-size than mysql defaults

---

api/launchers/stig-manager.bat
api/launchers/stig-manager.sh
api/source/utils/config.js
docs/installation-and-setup/envvars.csv

This PR changes the default values of `STIGMAN_CLIENT_USER_TIMEOUT` and `STIGMAN_CLIENT_ADMIN_TIMEOUT` to zero, which disables idle timeouts in the web app by default.
After initial consideration of #1701 we merged #1714 which changed the behavior of the web app so it would timeout users by default. After further consideration, we are defaulting to disabling idle timeout unless it is explicitly configured. This preserves long-standing existing behavior and acknowledges that the text of the specific STIG requirement referenced in #1701 may not be interpreted and applied identically by all deployments.

feat: idle timeouts default to zero

---

api/source/bootstrap/bootstrapUtils.js
api/source/utils/config.js

This pull request updates how the application sets `config.version` in `config.js`. If a `git describe` string is available via envvar `COMMIT_DESCRIBE`, it will be used to construct the semantic version string. If the describe string reports distance from a version tag (e.g. `1.5.10-15-gd937d97a`), the distance is appended as `+<distance>` as documented at [https://semver.org/](https://semver.org/). For the example, the resulting semantic version string is `1.5.10+15`.
The changes aim to make version handling more dynamic by leveraging environment variables and reducing direct dependencies on `package.json`.
* Modified `api/source/utils/config.js` to dynamically determine the version using the `COMMIT_DESCRIBE` environment variable, falling back to `package.json` if the environment …

feat: report semantic version with build

---

api/source/controllers/User.js
api/source/service/UserService.js
api/source/specification/stig-manager.yaml
client/src/js/SM/NavTree.js
client/src/js/SM/WhatsNew.js
test/api/mocha/data/user/user.test.js

This pull request simplifies the implementation of user web preferences which were introduced by #1722. It retains only two endpoints:
- `GET /user/web-preferences`
- `PATCH /user/web-preferences`
The changes streamline the codebase, reduce redundancy, and improve maintainability.
* Removed endpoints for specific web preference operations (`/user/web-preferences/keys`, `/user/web-preferences/keys/{key}`, and `PUT /user/web-preferences`) from `stig-manager.yaml`. The `PATCH /user/web-preferences` endpoint now handles all web preference updates. [[1]](diffhunk://#diff-9f0f1a173ef69bcbd3ddc0f420c723f60b94a56abbcba8b71f13bffe1c7b8788L3955-L3982) [[2]](diffhunk://#diff-9f0f1a173ef69bcbd3ddc0f420c723f60b94a56abbcba8b71f13bffe1c7b8788L4009-R3981)
* Removed related schemas (`WebPreferenceValue`, …

refactor: web-preferences

---

client/src/js/SM/NavTree.js
client/src/js/stigman.js

This PR introduces enhancements to the theme management system, enabling synchronization of dark mode state across browser tabs/windows and improving code clarity. The changes primarily focus on refactoring the Navigation Tree's Interface node structure, adding event listeners for theme updates, and broadcasting theme changes to other application browsing contexts.
* **Introduced `STIGMAN.webPreferencesChannel` for dark mode synchronization:** A new broadcast channel (`stigman-web-preferences`) was added to allow application browsing contexts to report when a theme change was made. The channel's message handler in `stigman.js` propagates a report to the rest of the application by firing the `themechanged` event. [ [`client/src/js/stigman.jsR80-R86`]](diffhunk://#diff-aa0f495e62a21b9363d882 …

feat: sync theme change across tabs

---

api/source/service/AssetService.js
api/source/specification/stig-manager.yaml

resolves: #1744 
Outputs cklb stigs[{version}] value as a string, rather than integer. 
This now matches STIG Viewer 3.5.1 output, and is compatible with eMASSter tool.

stig.version should be string value for cklb
