api/source/controllers/Asset.js
api/source/utils/writer.js
test/api/postman_collection.json

(fix) stigGrant projection #40

---

api/source/controllers/Review.js
api/source/service/mysql/ReviewService.js
api/source/specification/stig-manager.yaml
test/api/postman_collection.json

Fix for #12 
Introduced parameter `rules` to control the range of reviews that are returned

(fix) #47 ungranted reviews for lvl1

---

test/api/postman_collection.json

Added commented-out test for Issue #113
(Checks for 200 for appropriate users)

Added commented-out test for Issue #113

---

docs/Environment_Variables.md
docs/Technical_Info.md
docs/terminology.md

More info about workflow, possible configurations, and default db port update.

Documentation updates

---

.github/workflows/pub-docker.yml
docs/DockerHub_Readme.md

Address concerns from issue #122

Iron Bank base image in CD workflow

---

api/source/service/mysql/CollectionService.js
test/api/postman_collection.json

Reverts an undetected regression. 
@cd-rite Please review the new Postman tests, they are catching the regression and should be passing on this PR

fix: GET /collections/{collectionId}/poam fail with 500 (#141)

---

api/source/service/mysql/STIGService.js
api/source/specification/stig-manager.yaml
clients/extjs/css/stigman.css
clients/extjs/js/SM/Parsers.js
clients/extjs/js/SM/ReviewsImport.js
clients/extjs/js/init.js
clients/extjs/js/review.js
clients/extjs/js/stigmanUtils.js

Adds client-side parsing of CKL/XCCDF and a new interface for previewing and filtering imported reviews. In anticipation of future support for an NR result, supports 'notchecked' as a result and includes styling for displaying NR results in the future.

feat: Asset-STIG CKL import UI enhancements (#86)

---

api/source/controllers/STIG.js
api/source/controllers/User.js
api/source/service/mysql/CollectionService.js
api/source/utils/parsers.js

Addresses some items in issue #148

fix: increase test coverage

---

api/source/controllers/Asset.js
api/source/service/mysql/AssetService.js
clients/extjs/js/FileSaver.js
clients/extjs/js/collectionReview.js
clients/extjs/js/init.js

feat: Export Collection-STIG CKL archive

---

api/source/controllers/Operation.js
api/source/controllers/Review.js
api/source/controllers/STIG.js
api/source/index.js

feat: File uploads use memory storage

---

api/source/service/mysql/utils.js
clients/extjs/css/stigman.css
clients/extjs/js/SM/CollectionForm.js
clients/extjs/js/collectionAdmin.js
clients/extjs/js/collectionManager.js

fix: remove hard-coded reference to schema (#211)
feat: UI shows collectionId (#210)
feat: progress bar styling (#209)

Multiple issues

---

api/source/service/mysql/AssetService.js
api/source/service/mysql/utils.js

fix: reduce deadlock potential

---

clients/extjs/js/SM/FindingsPanel.js
clients/extjs/js/collectionAdmin.js
clients/extjs/js/completionStatus.js
clients/extjs/js/stigAdmin.js

Addresses Issues:
#202 
#200 
#201 
Related to #200 and #201, Collections Admin and STIG Admin grids had same issue, where export button was not working.
Fixed this as well.

fix: grid/store exports on finding details, status, stig, and collection reports

---

api/source/package-lock.json
api/source/package.json
api/source/utils/fetchStigs.js

disa site seemd to stop wanting to respond to requests made with old Request library. Switched fetchStigs to use "got" library for requests, altered scap regex to be more specific, as it was also grabbing the scc tools from that page.

bug: fixed issue fetching stigs and scap on init.

---

clients/extjs/css/stigman.css
clients/extjs/js/SM/Parsers.js
clients/extjs/js/collectionReview.js
clients/extjs/js/overrides.js
clients/extjs/js/review.js
clients/extjs/js/stigmanUtils.js

- fix: review form button behaviors, etc. (#215)
- feat: enable accept when selections include accept
- feat: CKL parser retains empty comments

Multiple fix and features

---

clients/extjs/js/SM/CollectionAsset.js

- Fix for #232 
- Show columns for values required by Navy SCA guidance

feat: Manage Assets -> multi-delete (#232), columns

---

clients/extjs/js/SM/ReviewsImport.js

fix: batch import continues on error, refreshes grids

---

api/source/index.js
api/source/service/mysql/AssetService.js
api/source/service/mysql/CollectionService.js
api/source/specification/stig-manager.yaml
api/source/utils/auth.js
api/source/utils/config.js
clients/extjs/js/SM/CollectionStig.js

Resolves #190 
Fixes #249 
Fixes #257 
Fixes #189 
Fixes #147 
Fixes #118 
Fixes #198

Multiple fixes and features

---

api/source/controllers/Asset.js
api/source/service/mysql/AssetService.js
api/source/specification/stig-manager.yaml
test/api/postman_collection.json

Endpoint updates

---

clients/extjs/js/SM/CollectionAsset.js

fix #298: Check for collectionId in event handlers

---

.github/workflows/pub-docker-ib.yml
.github/workflows/pub-docker.yml

Also adjusted alpine/ironbank workflow to use new IB build process. (Could also remove that part, and give them their own separate jobs entirely)
Also added IRONBANK_USERNAME and IRONBANK_CLI_TOKEN secrets to main repo.

Gave Iron Bank its own workflow file so it can be run independently

---

api/source/utils/auth.js

Verbose logging of AUTH bootstrap errors

---

api/source/index.js
api/source/utils/config.js

Format roles claim for optional chaining

---

api/source/service/mysql/ReviewService.js

fixes #355

---

api/source/service/mysql/migrations/lib/mysql-import.js

fix: use promise interface for conn.query() in mysql-import

---

clients/extjs/js/SM/NavTree.js

feat: All users can access Collection Review

---

clients/extjs/js/stigmanUtils.js

feat: continue on error when importing zips of STIGs

---

api/source/utils/fetchStigs.js

feat: continue on corrupted member of STIG zip

---

clients/extjs/js/SM/CollectionAsset.js
clients/extjs/js/SM/Global.js
clients/extjs/js/SM/TransferAssets.js
clients/extjs/js/collectionManager.js
clients/extjs/js/init.js

feat: UI for asset transfers

---

api/source/index.js
api/source/utils/config.js

Enable response validation with STIGMAN_DEV_RESPONSE_VALIDATION environment variable
Resolves: #129

Enable response validation with STIGMAN_DEV_RESPONSE_VALIDATION environment variable

---

api/source/controllers/STIG.js
test/api/postman_collection.json

fix: cci param fix, added checks for projections to tests

---

clients/extjs/js/init.js
clients/extjs/js/oidcProvider.js

feat: keep refreshing tokens

---

api/source/package-lock.json
api/source/package.json

deps: updating jwks-rsa to 2.0.4 removes axios

---

clients/extjs/js/SM/ReviewsImport.js

feat: relaxed CKL revision checks by default

---

api/source/controllers/Operation.js
api/source/index.js
api/source/package-lock.json
api/source/package.json
api/source/specification/stig-manager.yaml

feat: GET /op/definition endpoint with JSONPath

---

clients/extjs/js/SM/CollectionAsset.js
clients/extjs/js/SM/CollectionStig.js
clients/extjs/js/completionStatus.js
clients/extjs/js/stigmanUtils.js

feat: UI support for rejectedCount, minTs, maxTs

---

api/source/utils/auth.js

Construct userObject.display from token properties `name || username || servicename || 'USER`

feat: userObject.display tries username or servicename

---

clients/extjs/js/SM/CollectionStig.js

fix: filter grid on asset name

---

clients/extjs/js/SM/NavTree.js

fix: always sort Collection Review to top

---

api/source/specification/stig-manager.yaml

Added additionalProperties: False to most schemas, Added more required properties, marked return objects as arrays where appropriate and removed elsewhere, removed ReviewComplete, created a few more schemas where needed, corrected descriptions.
Implementation changes documented in issue #496

Various OAS changes to enable better response validation

---

api/source/service/mysql/AssetService.js

fix: CKL comments are exported

---

clients/extjs/css/stigman.css
clients/extjs/js/SM/NavTree.js
clients/extjs/js/collectionAdmin.js

Administration -> Application Management
Members -> Grants

feat: update UI labels

---

clients/extjs/css/stigman.css
clients/extjs/js/SM/CollectionAsset.js
clients/extjs/js/SM/CollectionForm.js
clients/extjs/js/collectionManager.js
clients/extjs/js/stigmanUtils.js

Style changes mostly to render better at 125% browser scaling

ui: styling tweaks

---

api/source/package-lock.json
api/source/package.json
api/source/service/mysql/AssetService.js

Includes update to swagger-ui-dist 4.1.3

chore: update node modules

---

CONTRIBUTORS.md
LICENSE.md

Updated copyright year range in `LICENSE.md`
Updated copyright year range for regular contributors in `CONTRIBUTORS.md`

chore: increment copyright year

---

api/source/service/mysql/CollectionService.js

refactor: JSON_EXTRACT() instead of JSON_VALUE()

---

api/source/index.js
client/src/js/SM/MainPanel.js

fix: escape quotes in Welcome title and message

---

client/src/css/stigman.css
client/src/js/SM/NavTree.js
client/src/js/SM/StigRevision.js

- Resolves #532 
- restyles tooltips

fix: register xtype for STIG revision grid

---

.github/workflows/api-tests.yml

Newman API testing does not cover the web client source

refactor: remove client from event path

---

api/source/package-lock.json
api/source/package.json
release-notes.rst

Commits:
- 13e4d1a dev: api distribution build script (#541)
- 434e984 refactor: remove client from event path (#540)
- b1903c6 fix: register xtype for STIG revision grid (#539)
- bb374d1 fix: escape quotes in Welcome title and message (#538)
- 459ef3e refactor: JSON_EXTRACT() instead of JSON_VALUE() (#537)
- 19892dc chore: increment copyright year (#536)
- d93bb4d chore: update node modules (#535)
- 7fad835 dev: client distribution build script (#534)
- dff8a9e feat: JSON logging and supporting code (#530)
- 3ac29a5 docs:  updated Logging, Environment Variables, Setup and Deployment docs. (#524)
Introduces:
- structured logging output from the API as a JSON stream
- build script to generate a minimized client distrubution
- build script to generate signed binaries of the API for Windows …

release: 1.2.0

---

api/source/controllers/Operation.js
api/source/specification/stig-manager.yaml
api/source/utils/auth.js
api/source/utils/config.js
docs/installation-and-setup/envvars.csv

remove: CORS proxy for OIDC

---

client/src/js/collectionReview.js

Property name in UI was not updated with changes made by commit 675e0317

fix: accept button incorrectly hidden

---

client/src/js/ExportButton.js

Resolves #575
Adds trim() to string processing chain in gridToCsv()

feat: ExportButton trims values

---

api/source/utils/logger.js

Include the request body when STIGMAN_LOG_LEVEL = 4

feat: log request body when logLevel = 4

---

client/src/js/SM/Parsers.js
client/src/js/SM/ReviewsImport.js

fix: xccdf import logic

---

api/source/service/mysql/AssetService.js

fix: CKL export fails to include all rules

---

client/src/js/SM/CollectionAsset.js
client/src/js/SM/CollectionStig.js

fix: headers don't match API

---

api/source/controllers/Review.js
client/src/js/SM/Review.js
test/api/postman_collection.json

fix: require a compliance result to submit review

---

api/source/package-lock.json
api/source/package.json
release-notes.rst

Changes:
- (API/App) Release of new Asset Labelling feature. Tag Assets in a Collection with Labels 
- (App) Navigation Tree filtering on Asset Labels. 
- (App) Asset Labels are now displayed in various places in UI. 
- (Docs) Documentation for new Asset Label feature available. See sections on the [Navigation Tree](https://stig-manager.readthedocs.io/en/latest/user-guide/user-guide.html#navigation-tree>) and [Collection Management - Labels](https://stig-manager.readthedocs.io/en/latest/user-guide/user-guide.html#labels-tab).
- (App) Adjusted language used in Review Panel Attribution box for clarity.
- (App) Restricted Collection modification options available in Application Management interface to better reflect overall application security approach. 
- (App) Adjusted line spacing to …

chore: bump release to 1.2.5

---

.github/workflows/api-tests.yml
api/source/service/mysql/AssetService.js
api/source/service/mysql/CollectionService.js
api/source/service/mysql/ReviewService.js

Rewrite queries to support MySQL < 8.0.24

refactor: coalesce for mysql 8.0.14

---

client/src/js/SM/FindingsPanel.js
client/src/js/SM/NavTree.js
client/src/js/completionStatus.js
client/src/js/findingsSummary.js
client/src/js/review.js

feat: dblclick on a Status/Finding row opens the corresponding Review tab

---

api/source/service/mysql/AssetService.js
api/source/service/mysql/OperationService.js
api/source/service/mysql/ReviewService.js
api/source/service/mysql/migrations/0014.js
api/source/service/mysql/utils.js
api/source/specification/stig-manager.yaml
test/api/postman_collection.json

**includes MySQL migration**
- Resolves #629.
- Refactored all methods in AssetService.js
- Introduced utility method `makeQueryString()` to eventually reduce repetition in the service files.

feat: `resultEngine` property added to Review schema

---

client/src/js/SM/Review.js
client/src/js/review.js

Resolves #645 
Adds "Accept" button to Asset/STIG review panel if user has an appropriate grant

feat: accept button in asset review panel

---

api/source/specification/stig-manager.yaml

fix: added schema "CollectionStatistics" for statistics property in the Collection(s)Projected response schema.  

---

client/src/js/SM/Review.js
client/src/js/review.js

Resolves #668 
Resolves #669 
Resolves #671

fix: resultEngine sprite; saving on tab close

---

api/source/utils/logger.js

In accordance with V-222478 of the Application Security and Development STIG, include the full response body when logging elevated requests.

feat: log response body for elevated requests

---

client/src/css/dark-mode.css
client/src/css/stigman.css
client/src/js/RowExpander.js
client/src/js/SM/FindingsPanel.js
client/src/js/SM/Global.js
client/src/js/collectionAdmin.js
client/src/js/collectionReview.js
client/src/js/review.js
client/src/js/stigmanUtils.js

Resolves #222
Currently uses a static value for truncation at 256 characters. Could expose the truncation limit in a future UI settings dialog (see issue #618)

feat: truncate oversized commentary text 

---

api/source/controllers/STIG.js

fix: update SCAP map.

---

api/source/package-lock.json
api/source/package.json
release-notes.rst

chore: updates for 1.2.10 release

chore: updates for 1.2.10 release

---

client/build.sh
client/src/js/SM/State.js
client/src/js/init.js
client/src/js/stigman.js

- Implementation of `SM.State.LocalStorageProvider`, a custom Ext.state.Provider that writes to `localStorage`.
- Sets the application state provider to an instance of `SM.State.LocalStorageProvider`

feat: localStorage state provider

---

client/src/js/SM/WhatsNew.js

Sets the width of What's New content div to 800px and the popup window to 850px

feat: what's new width

---

api/source/controllers/Collection.js
api/source/controllers/Operation.js
api/source/index.js
api/source/package-lock.json
api/source/package.json

GZip compress responses except where `req.noCompress` is truthy
Resolves: #777

feat: compress API responses

---

api/source/service/mysql/MetricsService.js
api/source/specification/stig-manager.yaml
client/build.sh
client/src/js/BufferView.js
client/src/js/SM/CollectionAsset.js
client/src/js/SM/CollectionStig.js
client/src/js/SM/ColumnFilters.js
client/src/js/SM/Metrics.js
client/src/js/collectionManager.js
client/src/js/collectionReview.js
client/src/js/init.js
client/src/js/review.js

Resolves #790 by changing the endpoint used by Collection Manage -> Assets to a Metrics endpoint
- adds extra properties (ip, mac, fqdn) to the response for Metrics aggregated by Asset 
Resolves #794 
- adds a simple BufferView class to buffer the rendering of several grids 
- Collection Manage -> Assets grid
- parent/child Metrics grids
- Collection Review -> reviews grid 
- Review -> other assets grid

feat: bufferview for several grids

---

client/src/js/BufferView.js
client/src/js/ExportButton.js

Resolves #815
Adds support for exporting CSV from grids with the recently introduced BufferView.

fix: ExportButton for BufferView grids

---

client/src/css/stigman.css

Style the load mask message so it is centered in the masked element

feat: center load mask text in element

---

api/source/package-lock.json
api/source/package.json
release-notes.rst

chore: updates for Release 1.2.19

chore: updates for Release 1.2.19

---

api/pkg.config.json
client/src/js/review.js

.... so that it won't error if not already loaded.  
fix: Added explicit asset csv-stringify to build config to ensure it is included in package.
Resolves: #826

fix: added conditional chain to groupGrid for datachanged handler.

---

api/source/service/mysql/OperationService.js

Importing appdata fails with a Review whose reviewHistory serializes into JSON > 5000 characters. This PR resolves this with custom handling of the bind params for the reviewHistory query.

fix: accept reviewHistory JSON > 5000 characters

---

api/source/package-lock.json
api/source/package.json

Updates all minor-level changes to dependencies.
Express package update addresses CVE-2022-24999
More info: https://nvd.nist.gov/vuln/detail/CVE-2022-24999#vulnCurrentDescriptionTitle

Update node package dependencies

---

client/src/js/userAdmin.js

Added CSV export button to User App Admin panel.

---

client/src/js/SM/CollectionForm.js

fix: userGrantsGrid behavior in windowed panel

---

api/source/service/mysql/AssetService.js
api/source/service/mysql/CollectionService.js
api/source/specification/stig-manager.yaml
client/src/css/stigman.css
client/src/js/SM/Global.js
client/src/js/SM/Library.js
client/src/js/collectionReview.js
client/src/js/review.js

feat: include rule.version (stigId) in checklists

---

client/src/js/SM/ReviewsImport.js

fix: Don't try to POST reviews if the review Array is empty. 
Resolves: #738

fix: Don't try to POST reviews if the review Array is empty. Resolves: #738

---

docs/installation-and-setup/db.rst

Added another suggested DB configuration option. (innodb_buffer_pool_size > 256M)

Added another suggested mysql config setting (innodb_buffer_pool_size> 256M)

---

client/src/css/stigman.css
client/src/js/SM/CollectionPanel.js
client/src/js/overrides.js

Make grid text selectable

---

.github/workflows/api-audit-test-coverage-response.yml
.github/workflows/api-container-tests.yml
.github/workflows/build-binary-artifacts.yml
.github/workflows/build-client.yml
.github/workflows/build-docs.yml
.github/workflows/pub-docker.yml

Added coverage report generation, pinned workflow actions, build artifact generation workflows.
Resolves: #940

Workflow updates

---

api/source/service/mysql/CollectionService.js

Addresses #833 
Rewrote query to perform about 33% faster. Tested with 2000 assets mapped to a Windows 10 STIG having 257 checks (514,000 reviews).  On test system, query time reduced from ~17 seconds to ~11 seconds.

refactor: collection checklist query

---

.github/workflows/api-container-tests.yml
.github/workflows/pub-docker.yml

switched to iron bank node-slim base image, updated upload-artifact actions to v3

switched to iron bank node-slim base image, updated upload-artifact actions to v3

---

client/src/js/SM/CollectionGrant.js

user admin -> user properties -> collection grants grid not allowing owner grant modifications

---

.github/workflows/pub-docker.yml

revert to IB node based on full ubi, awaiting fix for slim

---

api/source/service/mysql/MetricsService.js
api/source/specification/stig-manager.yaml

assessment severity breakouts for metrics

---

api/source/controllers/Asset.js
api/source/controllers/Collection.js
api/source/package-lock.json
api/source/package.json
api/source/utils/parsers.js

- Updates `package.json` from `^3.17.4` to `^4.2.4`
- Migrates our API code which requires `fast-xml-parser`  from their v3 api to their v4 api

chore: upgrade to fast-xml-parser v4.2.4

---

api/source/index.js

feat: add stack trace to API error responses

---

api/source/controllers/User.js
api/source/specification/stig-manager.yaml
client/src/js/SM/Collection.js
client/src/js/SM/CollectionAsset.js
client/src/js/SM/NavTree.js
client/src/js/collectionAdmin.js
client/src/js/userAdmin.js
test/api/postman_collection.json

chore: oas/test cleanup - removed elevate where not needed, adjusted tests
resolves: #370 
resolves: #413

chore: oas/test cleanup - removed elevate where not needed, adjusted tests

---

client/src/js/collectionAdmin.js

error introduced in last commit

pass collectionId when modifying from admin menu

---

api/source/controllers/Collection.js
api/source/service/mysql/STIGService.js

fix: streaming archive uses default revision strings

---

api/source/controllers/Asset.js
api/source/controllers/Collection.js
api/source/utils/escape.js

fix: xml double-encoding regression after upgrading fast-xml-parser

---

api/source/utils/parsers.js

fix: handle missing description in xccdf benchmark

---

client/src/js/SM/Library.js

Added CCIs column to STIG Library

---

api/source/controllers/Asset.js
api/source/service/mysql/AssetService.js
api/source/specification/stig-manager.yaml
client/src/js/SM/CollectionAsset.js
test/api/postman_collection.json

Resolves #1085 
Transferring an Asset will also transfer the Asset's label(s).
If a label with the same name exists in the destination Collection, the transferred Asset will be mapped to that label in the destination. The destination Collection label will retain its current description and color setting. 
If a label with the same name does not exist in the destination Collection, a label will be created in the destination Collection with the name, description, and color setting taken from the source Collection. The transferred Asset will then be mapped to this new label.

feat: transfer labels along with an asset

---

client/src/js/SM/AssetSelection.js

Additional tweak to fix implemented in #1120

fix: changed calculation to find longest item in STIGs array

---

client/src/js/SM/Parsers.js

fix: changed instanceof check to typeof check for .cklb stig_id and release_info processing

---

api/source/controllers/Collection.js
api/source/service/mysql/AssetService.js
test/api/postman_collection.json

fix: Check Asset labelIds for invalid values

---

client/README.md
docs/the-project/clients.rst
docs/the-project/related-repos.rst
docs/the-project/testing.rst
test/api/README.md

Updates docs to better describe building the client, testing, and related repos. Added readme to client folder.
Resolves: #1195

Updates docs to better describe building the client, testing, and related repos. Added readme to client folder.

---

docs/STIG-Manager-OSS.ckl

Due to minor changes in check content, not all V5R3 rules were populating with Reviews from the V5R1 .ckl when imported. Manually updated V5R3 version.
Resolves: #1090

Updated stigman ASD .ckl to V5R3

---

docs/installation-and-setup/db.rst
docs/installation-and-setup/installation-and-setup.rst
docs/the-project/requirements-and-dependencies.rst

docs: mysql supported versions, update guidance.

---

client/src/js/SM/CollectionForm.js

fix: Use PUT instead of PATCH for metadata updates

---

api/source/specification/stig-manager.yaml

Addresses: #1097 
This PR introduces a factor of our API specification with a focus on leveraging YAML's re usability and standardize our data types across the specification.

Refactor: Enhance API specification for better usability

---

client/src/js/SM/StigRevision.js

fix: request to GET /stigs should be elevated from stigAdmin UI to reflect accurate usage stats
resolves: #1264

fix: request to GET /stigs should be elevated from stigAdmin UI to reflect accurate usage stats

---

docs/installation-and-setup/envvars.csv

docs: STIGMAN_CLIENT_WELCOME_IMAGE usage clarification

---

client/src/js/SM/Exports.js

Resolves #1285 
This PR replaces the web app requests to `/collection/{collectionId}/status` with requests to `/collection/{collectionId}/metrics/summary` and refactors the subsequent logic that creates leaf nodes for the tree.

hotfix: replace web app requests to removed `/status` endpoint

---

client/src/js/appDataAdmin.js

feat: load mask for deployment details panel

---

api/source/service/OperationService.js
api/source/utils/auth.js
api/source/utils/logger.js
test/api/postman_collection.json

fixed bug mutating opstats object by creating a deeply cloned working copy;
More deployment details: added user/role counts, unique users to operationId counts, date generated, version/commit info, label usage, elevated request count
cleanup: flattened structure of some stat objects, moved code to functions, rolled individual "byCollection" counts into "countsByCollection" property

fix/feat: fixed bug mutating opstats object; added yet more details to deployment report

---

api/source/service/CollectionService.js

This PR rewrites the JOIN conditions for the query in getCollectionLabels() to improve performance by ~5x (in my setup).

refactor:  better joins in getCollectionLabels()

---

api/source/service/utils.js

docs were already updated, but db init check was not.
Resolves: #1017

chore: update minMySqlVersion to 8.0.21

---

docs/installation-and-setup/db.rst

docs: clarify mysql connection config info

---

api/source/service/utils.js

Resolves #1397 
Tested against reported version string `8.0.39-0ubuntu0.24.04.2`

fix: handle ported mysql version string from some distros

---

.github/workflows/api-audit-test-coverage-response.yml
.github/workflows/api-container-tests.yml

Renames the workflows to hopefully display more concisely when reported in PRs.

refactor: workflow names for display in PRs

---

api/source/package-lock.json
api/source/package.json

ran npm install to update other dependencies according to package.json

Update archiver to latest version

---

api/source/service/migrations/0034.js

Adds an index for the `state` column to the `asset` and `collection` tables.

feat: add index for asset/collection state column

---

test/api/mocha/data/asset/assetGet.test.js
test/api/mocha/data/asset/assetPost.test.js
test/api/mocha/data/asset/assetPut.test.js
test/api/mocha/data/collection/collectionDelete.test.js
test/api/mocha/data/collection/collectionGet.test.js
test/api/mocha/data/collection/collectionPatch.test.js
test/api/mocha/data/collection/collectionPost.test.js
test/api/mocha/data/collection/collectionPut.test.js
test/api/mocha/data/review/reviewGet.test.js
test/api/mocha/data/user/user.test.js
test/api/mocha/integration/collection.test.js
test/api/mocha/integration/deleteHandling.test.js
test/api/mocha/utils/testUtils.js

Resolves: #1381 
Removes use of Math.random() for random item creation in favor of uuid library.

fix: fixes tests to use uuid

---

.github/workflows/pub-docker.yml

Resolves #1468
Build and publish our Alpine-based container image for both x86 and arm64 (aarch64) architectures.

feat: build x86 and arm64 alpine-based image

---

client/src/js/SM/MetaPanel.js

UI: fix for missing meta panel labels, double-click behavior

---

api/source/package-lock.json
api/source/package.json

chore: updates for release 1.5.2

chore: updates for release 1.5.2

---

api/source/package-lock.json
api/source/package.json
release-notes.rst

release notes missing from last update

Release 1.5.2 notes

---

docs/requirements.txt

pr should trigger docs rebuild for test

pin sphinx version

---

test/api/mocha/data/metrics/metricsGet.js
test/api/mocha/data/metrics/metricsGet.test.js

resolves: #1379
adds tests for labelMatch=null & metrics on empty collections.

tests: adds missed tests for metrics

---

test/api/mocha/data/user/user.test.js

adds testing for admin and create_collection privileges on /user endpoints

test: adds missing test cases for admin and create_collection

---

api/source/bootstrap/bootstrapUtils.js
api/source/bootstrap/client.js
api/source/bootstrap/dependencies.js
api/source/bootstrap/docs.js
api/source/bootstrap/errorHandlers.js
api/source/bootstrap/middlewares.js
api/source/bootstrap/server.js
api/source/index.js
api/source/service/utils.js
api/source/utils/auth.js

resolves #1502 
still in draft

refactor: modularizes index.js

---

api/source/specification/stig-manager.yaml

resolves #1523 
This PR corrects and creates openAPI schema around the getAppInfo endpoint

refactor: creates proper api spec schema for getAppInfo

---

.github/workflows/api-state-tests.yml
api/source/package-lock.json
api/source/package.json
api/source/service/utils.js
api/source/utils/PoolMonitor.js
test/state/drop-db.sh
test/state/mocha/lib.js
test/state/mocha/outage.test.js

Resolves #1507
Implemented as per issue.

feat: handle database outages

---

client/src/js/modules/package-lock.json
client/src/js/modules/package.json
test/api/package-lock.json
test/api/package.json

Part of #1533 
Updates stig-manager-client-modules to get AssetParser class.

deps: update stig-manager-client-modules for CSV parser.

---

api/source/controllers/User.js
client/src/js/SM/User.js
test/api/mocha/integration/userStatus.test.js

allow grants/groups to be set for currently unavailable user if request is also setting them to "available"

---

client/src/js/review.js

resolves #881 
This pull request refactors the `addReview` function in `client/src/js/review.js`.
* Updated the default `activeTab` to `history-tab` instead of `other-tab` . When switching to the `other-tab`, the code now fetches and displays reviews on other assets for the selected rule,.

refactor: fetch 'other assets' on render of that  tab.

---

api/source/package-lock.json
api/source/package.json
release-notes.rst

chore: updates for 1.5.12
